[workspace]
members = [
    "kendryte-hal",
    "kendryte-rt",
    "kendryte-rt/macros",
    "xtask",
    "examples/peripherals/uart-demo",
    "examples/peripherals/gpio-blinky-demo",
    "examples/peripherals/gpio-button-demo"
]
